### ISSUE TITLE
iOS support is gone

### ISSUE THREAD

**Issue by BerkayDrsn** [psydack/uimgui#13]
Hi pysdack, as you know we are actively using your fork for imgui. As I see dylib for mac and ios builds are removed from the plugins folder. 

Can you provide the links of the used versions of ImGUI.NET, cimgui and imgui of sources so we can build it ourselves?

Also as a side note, if you wish to build them yourself and add to this repo, Apple doesn't allow dylib in the AppStore (not sure about the details we tried it with RG and got rejected from appstore). So a separate static library build is required for cimgui and some minor modifications needed to be done on the source so it points to the static library instead of the dynamic library. 

If you wish to give support for iOS, we can share our know-how back and forth.

**Comment by psydack** [comment]
Hello there.

I made a repository with the current ImGui.NET.
Could you check if it works for you?

As I'm quite busy this week I wouldn't let you guys waiting so I'll read
more carefully and reply properly anytime soon.

Sorry for being a bit rude and thanks for the info ;)

Em qua., 28 de jul. de 2021 às 12:48, Berkay Dursun <
***@***.***> escreveu:
