### ISSUE TITLE
ImPlot has jumbled text.

### ISSUE THREAD

**Issue by CaptainTimberTim** [psydack/uimgui#16]
Hi, 
I'm trying to use ImPlot but it seems that does not work properly. 
I saw that in the table of the ReadMe it only has a ~, but in the Issue where you 'introduced' implot it dies seem like it should work properly (https://github.com/psydack/uimgui/issues/2#issuecomment-873524663).
If I use the ShowDemoWindow.cs sample it looks like this: 
![image](https://user-images.githubusercontent.com/40162485/137890525-aaaf04cb-280f-4bd7-9579-8b37a1e1d2d2.png)
All the other stuff works properly, only the ImPlot text is wrong. (The window on the right, is the ImPlot demo window).

Maybe I am missing something... but Im not sure.

**Comment by psydack** [comment]
When I rebuild the plot's dll I made some mistake and I couldn't find what I did wrong. It is an issue.

**Comment by GeoSpark** [comment]
Has there been any movement on this? Is it a problem with Unicode or something, do you think? I don't mind getting my hands dirty to try to fix it, so any indication of where I might start looking would be great.

**Comment by psydack** [comment]
Sorry, no updates since last year. I'm having bad time to run things on mac. You could start looking how to build everything asescribed on readme.

**piece from readme**
You can build your [ImGui.NET](https://github.com/psydack/ImGui.NET) using my custom repo: ImGui.NET and [ImGui.NET-nativebuild](https://github.com/psydack/ImGui.NET-nativebuild)

**Comment by rtojagic** [comment]
@psydack @GeoSpark Hey, any progress here?

**Comment by Vivian-A** [comment]
It's not super helpful, but at [our custom fork](https://github.com/MarsVRLabs/RGS-ImGui-Fork), we have a working ImPlot dll. The build steps are a goddamn nightmare though, and I never got around to documenting them. If you desperately need ImPlot, I think our fork is the only one that has it functioning.

**Comment by smolten** [comment]
I wish ImGui.ShowDemoWindow() was not inside of a DLL
I want to be able to search for code in the demo window script like (I assume I could) if using C++ instead of Unity
Regardless, happy to have such a nice alternative to dealing with Unity RectTransforms

**Comment by psydack** [comment]
It seems fixed. Closing. Please, reopen if you need
