### ISSUE TITLE
ImPlot support?

### ISSUE THREAD

**Issue by bitsauce** [psydack/uimgui#2]
Hi there!

Good work on this repo btw! It's so nice to have ImGui working in Unity without a hassle.

One question I have is, have you considered adding [ImPlot](https://github.com/epezent/implot) to this package?

I actually compiled `cimgui`, `cimplot` and `ImPlot.NET` from scratch yesterday and added it to `uimgui`, but the end result was just having Unity crash when I try to use any `ImPlot` functions in Unity. I'm guessing the problem is that my compiler environment is not set up properly (compiler flags, etc.). Or maybe ImPlot won't work since it uses GPU acceleration?

Anyway, I was just curious if adding ImPlot is something you would consider for this repo?
Thanks

**Comment by psydack** [comment]
Hello!

Yes, I'm trying to compile ImGui.NET libs like implot, imnodes, etc, but seems to be very unstable and crash often even on ImGui.NET.
I can't tell what's wrong, but when I have anything I will push it. 

So, yeah, I'm planning to add the ImPlot.

Thank you.

**Comment by Vivian-A** [comment]
It's possible to do, check out https://github.com/TillAlex/ImGui.NET-nativebuild/tree/additional_libraries . I use it all the time inside of unity. It's a bit of a pain to set up, but I can send you the package I made to make it work inside of unity.

**Comment by Vivian-A** [comment]
Hm, unfortunately I don't have them running on the most recent version... Sorry about that! Though, it seems that https://github.com/mellinoe/ImGui.NET/pull/218#issuecomment-815097947 will help quite a bit!

**Comment by psydack** [comment]
I'm following that but isn't work yet. I will try a little more before bothering them. Thanks.

**Comment by viliwonka** [comment]
I got Implot working in Unity.

**Comment by viliwonka** [comment]
[Packages.zip](https://github.com/psydack/uimgui/files/6736957/Packages.zip)

Files for current package (including dlls)

**Comment by viliwonka** [comment]
Example code, hopefully all this will be sufficient.

`using ImGuiNET;
using ImPlotNET;
using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

    public class ExponentialDecayWindow : ImguiWindow {

        [Range(1f, 200f)]
        public int TicksPerSecond = 30;

        [Range(0.25f, 100f)]
        public float TotalTime = 10f;

        public float HalfLife = 1f;

        public float InitialValue = 10f;

        float decay;

        protected override void Awake() {

            base.Awake();

            WindowName = "Exponential Decay";
        }

        float Continious(float t) {

            return InitialValue * Mathf.Exp(-decay * t);
        }

        float DiscreteEuler(float value, float dt) {

            return -decay * value * dt;
        }

        float[] continiousArr ;
        float[] discreteArr   ;
        float[] timeArr       ;


        protected override void OnLayout() {

            if(Expanded = ImGui.Begin(WindowName, ref Open)) {

                // calculate decay from half life
                decay = Mathf.Log(2) / HalfLife;

                ImGui.DragInt("TicksPerSecond", ref TicksPerSecond, 10f, 5, 1000);
                ImGui.DragFloat("TotalTime", ref TotalTime, 0.5f, 0.1f, 100f);

                ImGui.DragFloat("Half Life", ref HalfLife, 0.05f, 0.001f, 10f);
                ImGui.DragFloat("Initial Value", ref InitialValue, 0.5f, -10f, 10f);

                float t = 0f;
                float dt = 1f / TicksPerSecond;

                int samples = Mathf.RoundToInt(TotalTime / dt);

                if(continiousArr == null || continiousArr.Length != samples) {
                    continiousArr = new float[samples];
                    discreteArr = new float[samples];
                    timeArr = new float[samples];
                }


                continiousArr[0] = InitialValue;
                discreteArr[0] = InitialValue;
                timeArr[0] = 0f;
                for(int i = 1; i < samples; i++) {

                    t += dt;
                    timeArr[i] = t;

                    continiousArr[i] = Continious(t);
                    discreteArr[i] = discreteArr[i - 1] + DiscreteEuler(discreteArr[i - 1], dt);

                }

                if(ImPlot.BeginPlot("Plot", "time", "value")) {

                    //ImPlot.SetNextPlotTicksX(ref time[0], 10000);
                    ImPlot.PlotLine("continious", ref timeArr[0], ref continiousArr[0], continiousArr.Length);
                    ImPlot.PlotLine("discrete", ref timeArr[0], ref discreteArr[0], discreteArr.Length);


                    ImPlot.EndPlot();
                }

                ImGui.End();
            }
        }

    }
`

**Comment by viliwonka** [comment]
Main modifications was in `ImGuiUnityContext.cs` with addition of ImPlot context that is "nested inside".

**Comment by psydack** [comment]
I managed to work with the most recent commit, but I wondering if I wait they release the new version - probably 1.84 - or if I make a branch to 1.82 with implot, etc without docking support, etc. The last option has some impact to rewrite a lot of code and that imply to not have freetype too. =/

**Comment by viliwonka** [comment]
My version I uploaded has docking support, works with ImPlot too (since it is part of window anyway).

As for rewriting Imgui.NET, in my experience just consists of changing vector2/3 to unity's vector2/3 afaik, but I believe u had more work done in it.

**Comment by psydack** [comment]
Had a more code to rewrite because I choose to work with Freetype and WCHAR. But we're having some progress. 
![image](https://user-images.githubusercontent.com/961971/124374099-bcfad300-dc6e-11eb-9716-e04b3b11673c.png)

=)

If someone want to test use this branch: https://github.com/psydack/uimgui/tree/feature/add-support-implot-imnodes-imguizmos

**Comment by psydack** [comment]
Now you can test imnodes too and imguizmo.
Sample for imnodes:
```cs
private void OnLayout(UImGui uImGui)
{
	if (ImGui.Begin("ImNodes window"))
	{
		imnodes.BeginNodeEditor();
		imnodes.BeginNode(1);

		imnodes.BeginNodeTitleBar();
		ImGui.TextUnformatted("simple node :)");
		imnodes.EndNodeTitleBar();

		imnodes.BeginInputAttribute(2);
		ImGui.Text("input");
		imnodes.EndInputAttribute();

		imnodes.BeginOutputAttribute(3);
		ImGui.Indent(40);
		ImGui.Text("output");
		imnodes.EndOutputAttribute();

		imnodes.EndNode();
		imnodes.EndNodeEditor();
		ImGui.End();
	}
}
```

I'm studying the best way to deploy and distribute these tools as addons.
Thank you, everyone.

**Comment by viliwonka** [comment]
Cool :D How is with imnodes support, afaik it requires tons of libraries (sdl ?)

**Comment by psydack** [comment]
It didn't require any lib to run but cimgui at least. If you want to see it what changes, check this comparison: https://github.com/psydack/uimgui/compare/main...feature/add-support-implot-imnodes-imguizmos
