### ISSUE TITLE
SetCamera-Method

### ISSUE THREAD

**Issue by ChrisLeister84** [psydack/uimgui#20]
Hey i really like you project, the only thing is, that currently it is not possible to set the used camera from the outside, and in OnEnable there is already a Fail-Check. It would be nice if we could set the camera after instantiating UImGui (UImGui.cs) as a prefab and then Reload. 

Is it possible to implement a SetCamera(Camera camera) - Method?

Best Regards

Chris

**Comment by psydack** [comment]
Hello.

Please, check if the branch linked I did support your suggestion. 

Thank you, I really appreciate. 
;)

**Comment by ChrisLeister84** [comment]
Yeah that should work :) Thanks

**Comment by slavanomics** [comment]
Using this method seems to result in an error for me.

I'm using the built in pipeline for context.

`AssertionException: Texture 1807609176952 does not exist. Try to use UImGuiUtility.GetTextureID().
Assertion failure. Value was False
Expected: True
UnityEngine.Assertions.Assert.Fail (System.String message, System.String userMessage) (at <ad50157ee00e45cdb3c8bd67012f8804>:0)
UnityEngine.Assertions.Assert.IsTrue (System.Boolean condition, System.String message) (at <ad50157ee00e45cdb3c8bd67012f8804>:0)
UImGui.Renderer.RendererMesh.CreateDrawCommands (UnityEngine.Rendering.CommandBuffer commandBuffer, ImGuiNET.ImDrawDataPtr drawData, UnityEngine.Vector2 fbSize) (at Library/PackageCache/com.psydack.uimgui@aea125f2a8/Source/Renderer/RendererMesh.cs:213)
UImGui.Renderer.RendererMesh.RenderDrawLists (UnityEngine.Rendering.CommandBuffer commandBuffer, ImGuiNET.ImDrawDataPtr drawData) (at Library/PackageCache/com.psydack.uimgui@aea125f2a8/Source/Renderer/RendererMesh.cs:100)
UImGui.UImGui.Update () (at Library/PackageCache/com.psydack.uimgui@aea125f2a8/Source/UImGui.cs:266)
`
Method is being called like so
`GetComponent<UImGui>().SetCamera(GameObject.FindGameObjectWithTag("Freecam").GetComponent<Camera>());`

**Comment by psydack** [comment]
What is your Unity version? Are you using drawing images?
I tried to replicate with Unity 2020.3.24f1 using the ShowDemoWindow and it works fine using the script:

```cs
private void Start()
{
	StartCoroutine(ChangeCameraCoroutine());
}

private IEnumerator ChangeCameraCoroutine()
{
	yield return new WaitForSeconds(5);

	GetComponent<UImGui.UImGui>().SetCamera(GameObject.FindGameObjectWithTag("Freecam").GetComponent<Camera>());
}
```

**Comment by slavanomics** [comment]
I'm using Unity 2021.2.7f1

Wrapping the method in a coroutine seems to have fixed the issue on my end. 
Only seems to happen for me if I run the method directly under a button press e.g. 
```cs
if (ImGui.Button("Freecam"))
{
GetComponent<UImGui>().SetCamera(GameObject.FindGameObjectWithTag("Freecam").GetComponent<Camera>());
}```

**Comment by psydack** [comment]
https://github.com/psydack/uimgui/tree/bugfix/on-change-camera-crash I think this might fix the error. If you have time to test it would be appreciated. Thanks

**Comment by slavanomics** [comment]
Can confirm the fix works. :)

Thank you very much.
