### ISSUE TITLE
FontCustomInitializer, in general, causes issues.

### ISSUE THREAD

**Issue by CantyCanadian** [psydack/uimgui#28]
When adding the package to my project for the first time, I get a NullReferenceException from UImGuiEditor.cs while adding the UImGui component. I was able to fix it by removing line 50 (EditorGUILayout.PropertyField(_fontCustomInitializer);).

**Comment by CantyCanadian** [comment]
It seems like the issue is locally, where the imgui dlls aren't loaded properly, which means ImGuiIOPtr causes issues.

**Comment by CantyCanadian** [comment]
After hammering on it for way too long (because your branch is honestly the best Unity ImGUI one available and I really want it to work), I managed to make it work by commenting everything related to _fontCustomInitializer.

This includes :
UImGuiEditor.cs:50 - Which prevented me from adding camera/shaders/style/etc.
TextureManaged.cs:119 to 123 - Which always broke.

Once those were commented, I can now use the package without issues.

**Comment by psydack** [comment]
Hello there.

I'm sorry to hear that. 
I'm trying to fix.

Thanks for using and reported it ;)

**Comment by psydack** [comment]
After some attempts I couldn't reproduce. I tried with URP and Built-In RP using 2020.3.24f1.
Could you share the steps to reproduce if it's possible and your unity version (and any other information).
If you could put images or paste the error here it would be great too.

Thanks.

**Comment by psydack** [comment]
I think I get it. 
Could you re-test please and share if the errors still happening?

Thank you.

**Comment by CantyCanadian** [comment]
Unfortunately, it doesn't solve the problem as you "cannot create an instance of the abstract type or interface". However, I found a way to fix it on my end (Unity 2019.4.34f1).

I don't think Unity can serialize a UnityEvent<ImGuiIOPtr> by default (I think due to ImGuiIOPtr being a non-serializable struct). So, I made a class inside UImGui inheriting from UnityEvent<ImGuiIOPtr>, tagged it as serializable, fixing the serialization issue and making it so you can assign a new object to it.

Here are the fixes in screenshot :

![image](https://user-images.githubusercontent.com/7960042/149684359-1afcb215-ddb7-4bf4-ba4d-75ab1a7f527f.png)
![image](https://user-images.githubusercontent.com/7960042/149684376-46f37e88-c730-47c0-ac44-8fc21c4d6d02.png)

**Comment by psydack** [comment]
Okay I see. It's because UnityEvent on 2019 hasn't a custom editor yet for non primitive types. 

Using your suggestion was easy to solve. 
Thanks for reporting.
