### ISSUE TITLE
Custom drawing doesn't work

### ISSUE THREAD

**Issue by Hirashi3630** [psydack/uimgui#32]
I tried recreating what [`imgui_demo.cpp`](https://github.com/ocornut/imgui/blob/master/imgui_demo.cpp#L7475) shows

```cs
ImGui.Begin(WindowName, ref IsWindowOpen, ImGuiWindowFlags.None);

ImDrawListPtr drawList = ImGui.GetWindowDrawList();

drawList.AddRect(new Vector2(10,10), new Vector2(20, 20), 1973790, 0.0f, ImDrawFlags.None, 2); 

ImGui.End();
```

but no luck...
I'm not sure if I'm doing something wrong or if it's a bug.

Unity 2020.3.25.f1
ImGUI 1.84 WIP
uimgui 4.1.0

**Comment by psydack** [comment]
Nice. Awesome to know that works.
In the end wasn’t a bug .

;)

Em seg., 7 de mar. de 2022 às 14:36, Hirashi3630 ***@***.***>
escreveu:
