### ISSUE TITLE
[BUG] Having issues with building a Unity project

### ISSUE THREAD

**Issue by Jake-NSW** [psydack/uimgui#33]
**Describe the bug**
Can't build a project that has this library, results in a load of errors. Pretty sure it has something to do with Unity not knowing what the external dependencies are when compiling.

**To Reproduce**
1. Build the project
2. Results in console

**Version/Branch of UImGui:**
Version: "4.1.1"

**Unity Version**
2021.2.6f1 & 2022.1b

**Render pipeline (HDRP / URP / Built-in)**
Built In

**Expected behavior**
Not throw a million errors when compiling

**Screenshots**
![image](https://user-images.githubusercontent.com/55055481/159190849-1a7806f4-6893-45e6-a1e7-6b94149d2761.png)

**Comment by psydack** [comment]
Hello there.

Could you share an image showing the uimgui package in your packages folder? 
I'm guessing somehow your project don't have the `uimgui/Plugin/ImGui.Net.dll`.

Thanks for reporting it.

**Comment by Jake-NSW** [comment]
![image](https://user-images.githubusercontent.com/55055481/159196657-056a0728-4383-4e94-8b64-e93d82735ab8.png)

**Comment by psydack** [comment]
Could you try to move uimgui from package to assets and see if it works?

**Comment by Jake-NSW** [comment]
Still throws the errors

**Comment by Jake-NSW** [comment]
Figured out the issue, it was because some of the .dll's didn't have x86 ticked. And I didn't realize I was building for 32x bit. Apologies for that.
