### ISSUE TITLE
[BUG] Invisible when camera environment background type is set to "Color"

### ISSUE THREAD

**Issue by iUltimateLP** [psydack/uimgui#38]
**Describe the bug**
The ImGui rendering disappears completley when you set the camera's environment background type to "Color".

**To Reproduce**
1. Set up a new project according to the README file of this repo
2. Add a camera
3. Set the camera's Environment > Background Type to "Color". The color itself does not matter
4. The ImGui will disappear.

**Version/Branch of UImGui:**
Version: 4.0.1

**Unity Version**
2021.2.11f1

**Render pipeline (HDRP / URP / Built-in)**
HDRP

**Expected behavior**
The UI should be visible.

**Comment by psydack** [comment]
Hello there. 

Thank you for reporting.
A reminder to anyone that might have this problem too, you can use 2 cameras (one to render UImGui).
