### ISSUE TITLE
[question] render ImGui above canvas in overlay mode

### ISSUE THREAD

**Issue by cholushkin** [psydack/uimgui#48]
Is there any idea of where I can start to change the code or maybe there is some settings to make ImGUI render on top of everything, including Unity GUI and its canvas in overlay mode?

**Comment by cholushkin** [comment]
I would like to use UImGUI as a debug gui (console, output values). But when I'm trying to use it such scenario the game UI canvas is rendered above my debug UIMGUI windows. I am using URP, mesh render

**Comment by lextatic** [comment]
Setup your UImGUI to render on a separate camera and then use this camera as a Stack camera of your Main Camera. There's no need to change any code and it works like a charm.

**Comment by psydack** [comment]
Closing after having no replies from OP

**Comment by tenpn** [comment]
fyi a simple stack didn't work for me in URP. the UI rendered last, whatever. I instead had to make a camera just for UI, change canvases to Screen Space - Camera, and put that camera in the stack.
