### ISSUE TITLE
Expressions in asmdef are invalid

### ISSUE THREAD

**Issue by prnthp** [psydack/uimgui#5]
The version definitions in the UImGui.asmdef are invalid and causes some hard to track down ArgumentException errors from some Unity packages. They should either be 1.0.0 or some range [1.0.0, 2.0.0], etc. https://docs.unity3d.com/Manual/ScriptCompilationAssemblyDefinitionFiles.html

**Comment by psydack** [comment]
Thanks for reporting. Are you saying about the versions from inputsystem, URP and HDRP?

**Comment by psydack** [comment]
Please, check out my commit https://github.com/psydack/uimgui/commit/e87d2ad3b0c11d3f07a3fe3edf9e91b2d2c2c9cc and see if it works. =)

**Comment by prnthp** [comment]
Yes it was exactly those. Can confirm that it works. Thanks!
