### ISSUE TITLE
[BUG] New package.json has invalid unity property

### ISSUE THREAD

**Issue by Dummiesman** [psydack/uimgui#57]
```
[Package Manager Window] Error adding package: https://github.com/psydack/uimgui.git.
Unable to add package [https://github.com/psydack/uimgui.git]:
  Manifest [REDACTED\Library\PackageCache\com.psydack.uimgui@ae7651beb4\package.json] is invalid:
    '2021.0' is not a valid `unity` property value. Expected '<year>.<version>'.
```

Since the last commit Unity does not let me import this in Unity 2021 LTS or 2022 LTS versions (at least)
In the interim it is possible to use the previous commit by using the package URL *
`https://github.com/psydack/uimgui.git#24efc5be254c10a34850bea0fcffaecccdcb5dee`
*if you remove ImGuizmo as it causes a native crash in this commit it appears

**Comment by psydack** [comment]
Ty
