### ISSUE TITLE
Using Unity Vector instead of System Vector type

### ISSUE THREAD

**Issue by BerkayDrsn** [psydack/uimgui#6]
Why is this package using the System's Vector class instead of the Unity's? RG.ImGui is using Unity Vector's in ImGUI wrapper layer. We tried to replace the package to yours from RG however it's not practical to cast every single System Vector to Unity Vector. And definitely not worth to write another ImGUI wrapper layer just for Unity compatibility.

Would be nice if you convert your imgui layer to use Unity types.

**Comment by psydack** [comment]
Hello. The main objective of using the c# default was to update ImGui.Net.dll easier and often without changing things like these. I made some tests and didn't see why not use System.Vector2. 

You can use something like that:

```cs
using NumericsConverter;
// ... 
var myUnityV2 = transform.positition;
var mySystemV2 = myUnityV2.ToSystem();
```

I can think, if it makes sense, do a layer to those methods using Unity.Vector, but surely I will not make this default.

Hope you understand.
Cheers.

**Comment by BerkayDrsn** [comment]
I mean It's a Unity package, and everytime you use something with a Vector you will have Unity Vector in your hands not the System one. And I think there is a valid case of using Unity types because ImGui utilizes lots of marshalling and almost every call using Vector is passed by ref. So even if you cast to System Vector, you will have to cast it back to Unity Vector back and forth. All those calls right now are dead basically. I believe a code generator that converts System type to Unity type after each ImGui.Net.dll update would be really useful but again I understand if it's out of scope of this project. Great work neverthless.

![image](https://user-images.githubusercontent.com/29129751/124657227-e99b2e80-deaa-11eb-964e-8957142bb808.png)

**Comment by psydack** [comment]
Hello.

I was reconsidering use Unity vectors instead of Numerics. I think that way we can nip a lot of problems in the bud. I made a fork from the original repo (ImGui.NET and ImGuiNET.nNative) so I can track any change easily and if anyone wants to help it will be easy too.

Could you help me to test the branch with this change https://github.com/psydack/uimgui/tree/feature/add-support-implot-imnodes-imguizmos? 

Thank you!
