### ISSUE TITLE
Missing Profiler.EndSample errors using HDRP + having Profiler window open.

### ISSUE THREAD

**Issue by CaptainTimberTim** [psydack/uimgui#7]
Hello, 

as soon as I open the Profiler window I get errors complaining that the BeginSample and EndSample count don't match.
This happens only if the RenderImGuiPass is added to the CustomPassVolume.
Maybe I'm doing something wrong, but I don't think so.

> Missing Profiler.EndSample (BeginSample and EndSample count must match): Custom Pass
>Previous 5 samples:
>	RenderLoop.CleanupNodeQueue
>	RenderTexture.SetActive
>	DearImGui.ExecuteDrawCommands
>	UImGui
>	RenderLoop.CleanupNodeQueue
>In the scope:
>	Custom Pass
>	HDRenderPipeline::Render Main Camera
>	Inl_Custom Pass
>	Inl_HDRenderPipeline::Render Main Camera
>	Inl_HDRenderPipelineAllRenderRequest

![image](https://user-images.githubusercontent.com/40162485/124725030-d15bfb80-df0c-11eb-81cd-204efa9a1b24.png)

Greetings, 
TJ

**Comment by psydack** [comment]
Hello there.

I did a fast test removing the markers and doesn't change the result. Seems to be a problem in the way we use the HDRP or even a Unity problem. I'll keep investigating. 

Thanks for reporting.

**Comment by CaptainTimberTim** [comment]
No problem. Keep up the good work!

One small thing, maybe you should check the "Using HDRP" section, as it seems not entirely correct, if I'm not mistaken.
The second point "Assign it to the render feature field of the DearImGui component." is not needed, or at least it works for me without it and the "render feature field" is not shown in the DearImGui component when using HDRP.

**Comment by psydack** [comment]
fixed 68561a1b5fc9fae7bcd500df8695e47c4adcd0c8
