### ISSUE TITLE
Is it possible to make it work in Unity 2019?

### ISSUE THREAD

**Issue by rtojagic** [psydack/uimgui#8]
Hey, I am having trouble using this in Unity 2019, there is an error in the Unity Collections dependency package, something about ReadOnly missing from the NativeArray.

**Comment by psydack** [comment]
Hello there.

I think the error you're saying happens because the original it uses a NativeArray to do some render stuff, like this:

```cs
// RendererMesh.cs or RendererProcedual.cs
// ... line160
// TODO: Convert NativeArray to C# array or list (remove collections).
NativeArray<ImDrawVert> vtxArray = NativeArrayUnsafeUtility.ConvertExistingDataToNativeArray<ImDrawVert>(
	(void*)drawList.VtxBuffer.Data, drawList.VtxBuffer.Size, Allocator.None);
NativeArray<ushort> idxArray = NativeArrayUnsafeUtility.ConvertExistingDataToNativeArray<ushort>(
	(void*)drawList.IdxBuffer.Data, drawList.IdxBuffer.Size, Allocator.None);
```

There is no workaround yet but If you rewrite those lines I'll be glad to merge with the main. =)

Thanks.

**Comment by rtojagic** [comment]
okay, I've cloned your project directly into the Assets of an empty Unity 2019 Project and it didn't complain about collections, rather it complained about the SetSubMeshes, as it didn't exist, so I had to set the meshes one by one in the loop above:

`					
       // [RenderMesh.cs]
	for (int i = 0, iMax = drawList.CmdBuffer.Size; i < iMax; ++i)
	{
		ImDrawCmdPtr cmd = drawList.CmdBuffer[i];
		SubMeshDescriptor descriptor = new SubMeshDescriptor
		{
			topology = MeshTopology.Triangles,
			indexStart = idxOf + (int)cmd.IdxOffset,
			indexCount = (int)cmd.ElemCount,
			baseVertex = vtxOf + (int)cmd.VtxOffset,
		};
		descriptors.Add(descriptor);
		_mesh.SetSubMesh(i, descriptor, NoMeshChecks);
	}

	vtxOf += vtxArray.Length;
	idxOf += idxArray.Length;
}
}

	_mesh.UploadMeshData(false);
`

![image](https://user-images.githubusercontent.com/8715031/125157899-dd92c380-e16d-11eb-8d82-b34a5bec4267.png)

**Comment by rtojagic** [comment]
Alright, I got it working without the NativeArrays.. I do not think it's the best way as it possibly affects performance but I can't tell how much.. plus I don't think there's another way.

Here's a screenshot of everything working with FPS, I'll do a pull request and then decide whether or not you want to use it, meanwhile I'll for the repo because I need this asap.

![image](https://user-images.githubusercontent.com/8715031/125161434-ab3f9100-e182-11eb-87c3-ea4d133401ef.png)

**Comment by psydack** [comment]
Wow, nice!

I'll test this into a different branch.

Thank you for your effort.

**Comment by rtojagic** [comment]
So to sum up...

I did some more testing, there are some more issues, for example while the code I wrote there fixes the compile error and it seems to be working, some parts of imgui features do not work as expected.. not sure if I can further investigate, however this concerns only the Mesh rendering type, you can go fine with Procedural.

About the NativeArray issues, I believe you can freely get rid of the dependency, test it out with your version of Unity to be sure, but here it works fine without it, because it's a built-in feature of Unity.

And that's pretty much it, in the end we just gotta fix that compile error and get rid of the dependency.

**Comment by psydack** [comment]
The original goal doesn't include the 2019 support, so I think the best way is to rip off render mesh for < 2020. 

Thanks again!

**Comment by rtojagic** [comment]
Sure, that will be quite enough! :) and np, doing this because I also need it hehe, might hear from me again :)
